# Stage 1 - Build
FROM node:iron-alpine3.18 as build

# Set up working directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Set environment variables
ENV NODE_ENV production
ENV HUSKY 0

# COPY yarn.lock /usr/src/app
# COPY package.json /usr/src/app

# Copy contents and install deps
COPY . /usr/src/app
RUN yarn install --frozen-lockfile

# Generate Prisma client
RUN npx prisma generate

# Copy the rest of the application code
COPY . .

# Build the Next.js application
RUN yarn build

# Stage 2 - Run
FROM node:iron-alpine3.18

# Copy the build artifacts from the builder stage
COPY --from=build /usr/src/app/next.config.js ./
COPY --from=build /usr/src/app/public ./public
COPY --from=build /usr/src/app/.next ./.next
COPY --from=build /usr/src/app/node_modules ./node_modules
COPY --from=build /usr/src/app/package.json ./package.json

# Metadata labels
LABEL maintainer="Zach Donnelly"
LABEL description="Noted"
LABEL version="1.0"

# Expose relevant port
EXPOSE 3000

# Start the application from generated build directory
CMD [ "yarn", "start" ]
